name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm ci  # Usar 'npm ci' es más apropiado para entornos de CI/CD

    # 4. Instalar los navegadores de Playwright
    - name: Install Playwright browsers
      run: npx playwright install

    # 5. Ejecutar las pruebas con Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # 6. Subir los resultados como artefacto
    - uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results
        retention-days: 20

    # 7. Obtener historial de Allure
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # 8. Generar el reporte de Allure
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    # 9. Desplegar el reporte a GitHub Pages
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./allure-report