name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci  # Usar 'npm ci' es más apropiado para entornos de CI/CD

      # 4. Instalar los navegadores de Playwright
      - name: Install Playwright browsers
        run: npx playwright install

      # 5. Ejecutar las pruebas con Playwright
      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      # 6. Obtener historial de Allure
      - name: Load Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 7. Generar reporte de Allure
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20

      # 8. Publicar reporte en GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GH_TOKEN }}

          publish_branch: gh-pages
          publish_dir: allure-history
