name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm install

    # 4. Instalar los navegadores de Playwright
    - name: Install Playwright browsers
      run: npx playwright install

    # 5. Ejecutar las pruebas con Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # 6. Instalar Allure para generar el reporte
    - name: Install Allure
      run: |
        npm install -g allure-commandline
        allure --version

    # 7. Guardar los resultados de la ejecución en el directorio de historial
    - name: Consolidate results
      run: |
        mkdir -p allure-results
        cp -r allure-report/* allure-results/ || true

    # 8. Generar el reporte de Allure con todos los resultados
    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

    # 9. Deploy a GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./allure-report
